{
  "hash": "33b5e42ef072cdb09c31abaa3317ddca",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Mini-Project 3: Simulation to Investigate Confidence Intervals\"\nformat: html\n---\n\n\n\n\n\n## N = 10\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 10   # sample size\np <- 0.45  # population proportion\n\n\ngenerate_samp_prop <- function(n, p) {\n  x <- rbinom(1, n, p) # randomly generate number of successes for the sample\n\n  ## number of successes divided by sample size\n  phat <- x / n\n\n  ## 95% confidence interval\n  lb <- phat - 1.96 * sqrt(phat * (1 - phat) / n)\n  ub <- phat + 1.96 * sqrt(phat * (1 - phat) / n)\n  \n  prop_df <- tibble(phat, lb, ub)\n  return(prop_df)\n}\n\ngenerate_samp_prop(n = n, p = p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n   phat      lb    ub\n  <dbl>   <dbl> <dbl>\n1   0.1 -0.0859 0.286\n```\n\n\n:::\n\n```{.r .cell-code}\n## how many ci's do we want?\nn_sim <- 5000\n\nprop_ci_df <- map(1:n_sim,\n    \\(i) generate_samp_prop(n = n, p = p)) |>\n  bind_rows()\n\nprop_ci_df |> mutate(coverage = if_else(p > lb & p < ub,\n                                   true = 1, \n                                   false = 0)) |> \n        summarise(avg_interval_width = mean(ub - lb),\n                        avg_coverage_rate = mean(coverage))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  avg_interval_width avg_coverage_rate\n               <dbl>             <dbl>\n1              0.583             0.882\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 10   # sample size\np <- 0.2  # population proportion\n\n\ngenerate_samp_prop <- function(n, p) {\n  x <- rbinom(1, n, p) # randomly generate number of successes for the sample\n\n  ## number of successes divided by sample size\n  phat <- x / n\n\n  ## 95% confidence interval\n  lb <- phat - 1.96 * sqrt(phat * (1 - phat) / n)\n  ub <- phat + 1.96 * sqrt(phat * (1 - phat) / n)\n  \n  prop_df <- tibble(phat, lb, ub)\n  return(prop_df)\n}\n\ngenerate_samp_prop(n = n, p = p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n   phat      lb    ub\n  <dbl>   <dbl> <dbl>\n1   0.2 -0.0479 0.448\n```\n\n\n:::\n\n```{.r .cell-code}\n## how many ci's do we want?\nn_sim <- 5000\n\nprop_ci_df <- map(1:n_sim,\n    \\(i) generate_samp_prop(n = n, p = p)) |>\n  bind_rows()\n\nprop_ci_df |> mutate(coverage = if_else(p > lb & p < ub,\n                                   true = 1, \n                                   false = 0)) |> \n        summarise(avg_interval_width = mean(ub - lb),\n                        avg_coverage_rate = mean(coverage))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  avg_interval_width avg_coverage_rate\n               <dbl>             <dbl>\n1              0.437             0.888\n```\n\n\n:::\n:::\n\n\n\n## N = 60\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 60   # sample size\np <- 0.45  # population proportion\n\n\ngenerate_samp_prop <- function(n, p) {\n  x <- rbinom(1, n, p) # randomly generate number of successes for the sample\n\n  ## number of successes divided by sample size\n  phat <- x / n\n\n  ## 95% confidence interval\n  lb <- phat - 1.96 * sqrt(phat * (1 - phat) / n)\n  ub <- phat + 1.96 * sqrt(phat * (1 - phat) / n)\n  \n  prop_df <- tibble(phat, lb, ub)\n  return(prop_df)\n}\n\ngenerate_samp_prop(n = n, p = p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n   phat    lb    ub\n  <dbl> <dbl> <dbl>\n1 0.433 0.308 0.559\n```\n\n\n:::\n\n```{.r .cell-code}\n## how many ci's do we want?\nn_sim <- 5000\n\nprop_ci_df <- map(1:n_sim,\n    \\(i) generate_samp_prop(n = n, p = p)) |>\n  bind_rows()\n\nprop_ci_df |> mutate(coverage = if_else(p > lb & p < ub,\n                                   true = 1, \n                                   false = 0)) |> \n        summarise(avg_interval_width = mean(ub - lb),\n                        avg_coverage_rate = mean(coverage))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  avg_interval_width avg_coverage_rate\n               <dbl>             <dbl>\n1              0.250             0.948\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 60   # sample size\np <- 0.2  # population proportion\n\n\ngenerate_samp_prop <- function(n, p) {\n  x <- rbinom(1, n, p) # randomly generate number of successes for the sample\n\n  ## number of successes divided by sample size\n  phat <- x / n\n\n  ## 95% confidence interval\n  lb <- phat - 1.96 * sqrt(phat * (1 - phat) / n)\n  ub <- phat + 1.96 * sqrt(phat * (1 - phat) / n)\n  \n  prop_df <- tibble(phat, lb, ub)\n  return(prop_df)\n}\n\ngenerate_samp_prop(n = n, p = p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n   phat    lb    ub\n  <dbl> <dbl> <dbl>\n1   0.3 0.184 0.416\n```\n\n\n:::\n\n```{.r .cell-code}\n## how many ci's do we want?\nn_sim <- 5000\n\nprop_ci_df <- map(1:n_sim,\n    \\(i) generate_samp_prop(n = n, p = p)) |>\n  bind_rows()\n\nprop_ci_df |> mutate(coverage = if_else(p > lb & p < ub,\n                                   true = 1, \n                                   false = 0)) |> \n        summarise(avg_interval_width = mean(ub - lb),\n                        avg_coverage_rate = mean(coverage))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  avg_interval_width avg_coverage_rate\n               <dbl>             <dbl>\n1              0.199             0.924\n```\n\n\n:::\n:::\n\n\n\n## N = 200\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 200   # sample size\np <- 0.45  # population proportion\n\n\ngenerate_samp_prop <- function(n, p) {\n  x <- rbinom(1, n, p) # randomly generate number of successes for the sample\n\n  ## number of successes divided by sample size\n  phat <- x / n\n\n  ## 95% confidence interval\n  lb <- phat - 1.96 * sqrt(phat * (1 - phat) / n)\n  ub <- phat + 1.96 * sqrt(phat * (1 - phat) / n)\n  \n  prop_df <- tibble(phat, lb, ub)\n  return(prop_df)\n}\n\ngenerate_samp_prop(n = n, p = p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n   phat    lb    ub\n  <dbl> <dbl> <dbl>\n1 0.435 0.366 0.504\n```\n\n\n:::\n\n```{.r .cell-code}\n## how many ci's do we want?\nn_sim <- 5000\n\nprop_ci_df <- map(1:n_sim,\n    \\(i) generate_samp_prop(n = n, p = p)) |>\n  bind_rows()\n\nprop_ci_df |> mutate(coverage = if_else(p > lb & p < ub,\n                                   true = 1, \n                                   false = 0)) |> \n        summarise(avg_interval_width = mean(ub - lb),\n                        avg_coverage_rate = mean(coverage))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  avg_interval_width avg_coverage_rate\n               <dbl>             <dbl>\n1              0.138             0.942\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 200   # sample size\np <- 0.2  # population proportion\n\n\ngenerate_samp_prop <- function(n, p) {\n  x <- rbinom(1, n, p) # randomly generate number of successes for the sample\n\n  ## number of successes divided by sample size\n  phat <- x / n\n\n  ## 95% confidence interval\n  lb <- phat - 1.96 * sqrt(phat * (1 - phat) / n)\n  ub <- phat + 1.96 * sqrt(phat * (1 - phat) / n)\n  \n  prop_df <- tibble(phat, lb, ub)\n  return(prop_df)\n}\n\ngenerate_samp_prop(n = n, p = p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n   phat    lb    ub\n  <dbl> <dbl> <dbl>\n1 0.185 0.131 0.239\n```\n\n\n:::\n\n```{.r .cell-code}\n## how many ci's do we want?\nn_sim <- 5000\n\nprop_ci_df <- map(1:n_sim,\n    \\(i) generate_samp_prop(n = n, p = p)) |>\n  bind_rows()\n\nprop_ci_df |> mutate(coverage = if_else(p > lb & p < ub,\n                                   true = 1, \n                                   false = 0)) |> \n        summarise(avg_interval_width = mean(ub - lb),\n                        avg_coverage_rate = mean(coverage))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  avg_interval_width avg_coverage_rate\n               <dbl>             <dbl>\n1              0.110             0.940\n```\n\n\n:::\n:::\n\n\n\n## Large Sample Assumptions\n\nn = 10\n\np\\*n = 0.45x10 = 4.5 (1-p)n = 0.55x10 = 5.5 does not hold\n\np\\*n = 0.2x10 = 2 (1-p)n = 0.8x10 = 8 does not hold\n\nn = 60\n\np\\*n = 0.45x60 = 27 (1-p)n = 0.55x60 = 33 holds\n\np\\*n = 0.2x60 = 12 (1-p)n = 0.8x60 = 48 holds but not by a large margin\n\nn = 200\n\np\\*n = 0.45x200 = 90 (1-p)n = 0.55x200 = 110 holds\n\np\\*n = 0.2x200 = 40 (1-p)n = 0.8x200 = 160 holds\n\n|            |               |  sn = 10  |  mn = 60  | ln = 200  |\n|:----------:|:-------------:|:---------:|:---------:|:---------:|\n| $p = 0.45$ | Coverage Rate |   0.876   |  0.9496   |  0.9534   |\n| $p = 0.2$  | Coverage Rate |   0.887   |  0.9246   |  0.9446   |\n|            |               |           |           |           |\n| $p = 0.45$ | Average Width | 0.5835463 | 0.2496143 | 0.1375476 |\n| $p = 0.2$  | Average Width | 0.4365931 | 0.1997524 | 0.110498  |\n\n: Table of Results {.striped .hover}\n\nStDev : sqrt(p(1-p)/n) Avg Width for 95% : 2\\*(1.96\\*stdev)\n\nFor our CI with a sample size of 10, we see that our average width is large, with a wide spread in the confidence interval. For both p levels, the large sample assumption does not hold, and our coverage rate is not 95%. If our p is equal to 0.45, we expect the width of our 95% CI to be 2\\* 1.96\\*sqrt((0.45(1-0.45))/10) = 0.6292. This is wider than our average width of 0.5835 for p = 0.45. This is why our coverage rate is less than 95%. For our p = 0.2, the large sample assumption also does not hold, so our average interval for a 95% confidence interval is wider than our sample average width. For our p = 0.2, our coverage rate of 88.7% is lower than the 95% confidence rate we would expect because our large sample size assumption does not hold. For our p = 0.45, the width of the CI is larger than 0.2, but the coverage rate is similarly different from 95%, because or large sample size assumption does not hold.\n\nFor a sample size of 60, we have a significantly smaller average width for our CI's, for both p levels. The large sample size assumptions do hold, with n being large enough for both p values. If our p is equal to 0.45, we expect the width of our 95% CI to be 2\\* 1.96\\*sqrt((0.45(1-0.45))/60) = 0.2517. This is very close to our sample average width for n = 60, which explains the coverage rate of nearly 95%, with 94.96%. For p = 0.2, we expect the width of our 95% CI to be 2\\* 1.96\\* sqrt((0.2(1-0.2))/60) = 0.2024. This is slightly more than our sample average width which explains the slightly lower coverage rate of p = 0.2. The large sample assumption in this case holds but only by a small margin which explains the coverage rate that is less than the cases that have larger assumptions. The coverage rate is still very close to 95% with this mid level sample size.\n\nFor a sample size of 200, we have even smaller average widths for our CIs, and coverage rates very close to 95%. If our p is equal to 0.45, we expect the width of our 95% CI to be 2\\* 1.96\\*sqrt((0.45(1-0.45))/200) = 0.1379. This is very close to our sample value for average width, with a coverage rate of 95.34%, very close to 95%. For p = 0.2, we expect the width of our 95% CI to be 2\\* 1.96\\* sqrt((0.2(1-0.2))/200) = 0.11087. This value is also very close to our sample average width, leading to a coverage rate of 94.46%, again very close to 95%. We see as our sample size increases, our expected average width and sample average width begin to match better, leading to coverage rates that approach 95%. We can see for small sample sizes where the large sample size assumption does not hold, the coverage rate and expected average width are not nearly as close to the simulated values.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}